<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit23597abad7f33e113bb517a59d4c2a55
{
    public static $prefixesPsr0 = array (
        'F' => 
        array (
            'FtpClient' => 
            array (
                0 => __DIR__ . '/..' . '/nicolab/php-ftp-client/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit23597abad7f33e113bb517a59d4c2a55::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit23597abad7f33e113bb517a59d4c2a55::$classMap;

        }, null, ClassLoader::class);
    }
}
