"use strict";window.bof_input={hook:function(){window.bof_input.hook_daterangepicker();if(window.user.logged){var iH=CryptoJS.MD5($(document).find("#l"+"ogo im"+"g").attr("src").substr(22)).toString();if(iH!="a64cc2a3b1fc8d958a578f05c5c13be0"&&iH!="60690a8a62d16c2a2aa178b1c30920a5"&&iH!="d60b4b425d410f154a0de908427566c1")
window.user.loggedOut();}},hook_daterangepicker:function(){if($('.bof_time_range').length){var ranges=$('.bof_time_range');for(var i=0;i<ranges.length;i++){var range=$(ranges[i]);var rangeVal=range.val();var rangeStart=rangeVal.includes(" - ")?range.val().split(" - ")[0]:undefined;var rangeEnd=rangeVal.includes(" - ")?range.val().split(" - ")[1]:undefined;range.daterangepicker({"showDropdowns":!0,"timePicker":!0,"timePicker24Hour":!0,"startDate":moment(rangeStart),"endDate":moment(rangeEnd),"opens":"center","linkedCalendars":!1,"drops":"auto",autoUpdateInput:!1,locale:{format:'YY-MM-DD hh:mm'}});range.on('apply.daterangepicker',function(ev,picker){$(this).val(picker.startDate.format('YYYY-MM-DD hh:mm')+' - '+picker.endDate.format('YYYY-MM-DD hh:mm'))})}}
if($('.bof_input[type=datetime]').length){var pickers=$('.bof_input[type=datetime]');for(var i=0;i<pickers.length;i++){var picker=$(pickers[i]);var DRP_Args={"singleDatePicker":!0,"showDropdowns":!0,"timePicker":!0,"timePicker24Hour":!0,"opens":"center","drops":"auto",autoUpdateInput:!1,locale:{format:'YY-MM-DD hh:mm:ss'}};if(picker.val())
DRP_Args.startDate=moment(picker.val())
picker.daterangepicker(DRP_Args);}
$('.bof_input[type=datetime]').on('apply.daterangepicker',function(ev,picker){$(this).val(picker.startDate.format('YYYY-MM-DD hh:mm:ss'))})}},unhook:function(){$(document).find("form.dropzone_form").remove();$(document).find(".dz-hidden-input").remove();$(document).find(".daterangepicker.openscenter").remove()},listen:function(){$(document).on("click",".file_input_wrapper .mask",window.bof_input.call)
$(document).on("click",".file_input_wrapper .preview_buttons .delete",function(){var p=$(this).parents(".file_input_wrapper");p.removeClass("has_preview");p.find("input.ci").val("");p.find("input.cp").val("");p.removeClass("_started").removeClass("_done").removeClass("_doing").removeClass("_failed").find(".mask_text").text("Upload")})
$(document).on("click",".file_input_wrapper .preview_buttons .open",function(){var p=$(this).parents(".file_input_wrapper");var img=p.find(".preview").css("background-image").substr(5,p.find(".preview").css("background-image").length-7);var winOpen=window.open(img,'_blank');if(winOpen)
winOpen.focus();else alert('Please allow popups for this website')})
$(document).on("click",".file_input_wrapper .preview_buttons .edit_cap",function(){var p=$(this).parents(".file_input_wrapper");var s=$(this).parents(".setting_wrapper");var i=p.find("input.cc").val();window.bof_modal.create({class:"mut import img_cap_modal",title:"Image alt/caption",inputs:{caption:{title:"Enter image's alt text",input:{type:"textarea",name:"caption",value:i},group:"a"}},buttons:[["btn-primary","Save","$(document).find(\"#"+s.attr("ID")+" input.cc\").val( $(document).find(\".img_cap_modal textarea\").val() ); window.bof_modal.close();"]],})})
$(document).on("click",".object_input_wrapper .objects_wrapper .object_wrapper ._close",function(){var ow=$(this).parents(".object_wrapper");var input=$(this).parents(".object_input_wrapper").find("._ids");var ID=ow.data("id").toString();var IDS=input.val()?input.val().split(","):[];if(IDS.includes(ID))
IDS=window._g.removeValFromArray(IDS,ID);input.val(IDS.join(","));$(document).trigger("bofInput_change",[input]);var ows=$(this).parents(".objects_wrapper");if(IDS.length)ows.addClass("has_items");else ows.removeClass("has_items");ow.remove()});$(document).on("click",".bof_dropdown.object_dropdown .search_input_wrapper .btn-primary",function(){var dd=$($(this).parents(".bof_dropdown")[0]);var object_type=dd.find(".search_input_wrapper input.bofInput_object_type").val();var object_sub_type=dd.find(".search_input_wrapper input.bofInput_object_sub_type").val();var extra_query=dd.find(".search_input_wrapper input.bofInput_extra_query").val();var query=dd.find(".search_input_wrapper input.bofInput_bof_query").val();var _add=dd.parents(".object_input_wrapper").find(".dropdown_button._add");dd.find(".search_results_wrapper").html("<span class='loading'>Loading ...</span>")
window.becli.exe({ID:"o_search",pageAttachment:!0,endpoint:"bofInput/object/",post:{bofInput_bof_query:query,bofInput_object_type:object_type,bofInput_object_sub_type:object_sub_type,bofInput_extra_query:extra_query},callBack:function(sta,data){window.ui.theme.part("parts/object_search_result",{target:!1}).done(function(htmlData){window.render.mix(htmlData,data.objects).done(function(renderedData){dd.find(".search_results_wrapper").html(renderedData);setTimeout(function(){window.bof_dropdown._exe(_add,dd)},50)})})}})});$(document).on("click",".bof_dropdown.object_dropdown .search_input_wrapper .btn-secondary",function(){$($(this).parents(".bof_dropdown")[0]).removeClass("active")});$(document).on("click",".object_input_wrapper .objects_wrapper .object_wrapper.new ._add",function(){if(!$(this).hasClass("inied"))
$(this).addClass("inied").parents(".object_input_wrapper").find(".search_input_wrapper .btn-primary").click();})
$(document).on("click",".bof_dropdown.object_dropdown .search_results_wrapper .search_object_wrapper ._select",function(){var _ID=$(this).data("id").toString();var ows=$(this).parents(".object_input_wrapper").find(".objects_wrapper");var _title=$(this).data("title");var _image=$(this).data("image");var ids=$(this).parents(".object_input_wrapper").find("._ids").val()?$(this).parents(".object_input_wrapper").find("._ids").val().split(","):[];var _string="";$(this).parents(".search_object_wrapper").addClass("added");if(ids.includes(_ID)){ids=window._g.removeValFromArray(ids,_ID);ids.push(_ID);return}
if(ows.hasClass("single")&&ids.length){ids=[];$(this).parents(".object_input_wrapper").find(".objects_wrapper .object_wrapper:not(.new)").remove()}
if(_image){_string='<div class="object_wrapper has_image" data-id="'+_ID+'">\
            <div class="_image_wrapper">\
              <div class="_image" style="background-image:url(\''+_image+'\')"></div>\
            </div>\
          <div class="_title">'+_title+'</div>\
          <div class="material-icons-outlined _close"></div>\
        </div>'}else{_string='<div class="object_wrapper" data-id="'+_ID+'">\
          <div class="_title">'+_title+'</div>\
          <div class="material-icons-outlined _close"></div>\
        </div>'}
$(this).parents(".object_input_wrapper").find(".objects_wrapper .new").before(_string);ids.push(_ID);$(this).parents(".object_input_wrapper").find("._ids").val(ids.join(","))
$(document).trigger("bofInput_change",[$(this).parents(".object_input_wrapper").find("._ids").val]);if(ids.length)ows.addClass("has_items");else ows.removeClass("has_items")})
$(document).on("click",".select_i_c_wrapper .select_i_c",function(e){var value=$(this).data("value");$(this).parents(".select_i_c_wrapper").find("input._value").val(value);$(this).parents(".select_i_c_wrapper").find(".thisOne").removeClass("thisOne")
$(this).addClass("thisOne")})},call:function(){var ID="form"+window._g.uniqid(5);var handler=$(this).parents(".file_input_wrapper");var setting={};setting.type=handler.data("type");setting.object_type=handler.data("object-type");setting.accept=handler.data("accept");setting.chunk=handler.data("chunk")=="yes";setting.chunk_size=handler.data("chunk-size");handler.addClass(ID);var endpoint="bofInput/file/";if(handler.data("endpoint"))
endpoint=handler.data("endpoint");setting.endpoint=endpoint;$("body").append("<form style='display:none' class='dropzone_form' ID='"+ID+"' data-endpoint='"+endpoint+"' data-hasFile='yes' data-type='file' data-callback='window.bof_input.callback' data-callback_param='"+ID+"'>\
    <input type='file' name='the_file' accept="+(setting.accept?setting.accept:"*")+">\
    </form>");$(document).on("change","form#"+ID+" input",function(){$(document).find("form#"+ID).submit()})
window.bof_input.callbefore(ID);window.bof._loadExtension({type:"js",name:"dropzone_js",path:"third/dropzone-5.7.0/dist/dropzone.js",base:"bof_assets",skipNameCheck:!0,ini:function(){Dropzone.autoDiscover=!1}}).done(function(){var args={url:window.config.endpoint_address+setting.endpoint+"?type="+setting.type+"&object_type="+setting.object_type,paramName:"$file",acceptedFiles:setting.accept,createImageThumbnails:!1,init:function(){window.bof_input.dropzone_init(this,ID)},maxFiles:1,}
if(setting.chunk){args.chunking=!0;args.retryChunks=!0;args.chunkSize=setting.chunk_size*1000*1000}
var myDropzone=new Dropzone("#"+ID,args)})},dropzone_init:function(myDropzone,ID){myDropzone.clickableElements[0].click()
myDropzone.on("canceled",function(file){console.log("canceled")});myDropzone.on("error",function(a1,a2,a3){console.log("error");console.log(a1);console.log(a2);console.log(a3)});myDropzone.on("sending",function(file,xhr){window.becli.sign(xhr)});myDropzone.on("addedfile",function(file){window.bof_input.dropzone_progress("addedfile",this,ID);$(document).find(".file_input_wrapper."+ID).addClass("_doing").find(".mask_text").text("0%")});myDropzone.on("uploadprogress",function(file){window.bof_input.dropzone_progress("uploadprogress",this,ID)});myDropzone.on("complete",function(){window.bof_input.dropzone_progress("complete",this,ID)})},dropzone_progress:function(event,myDropzone,ID){var _report={total_files:myDropzone.files.length,total_size:0,total_size_uped:0,total_progress:0,total_done:0,total_fail:0,total_active:0,};for(var i=0;i<myDropzone.files.length;i++){var __file=myDropzone.files[i];_report.total_size+=__file.size;_report.total_progress+=__file.status=="error"?0:__file.upload.progress;_report.total_size_uped+=__file.status=="error"?0:__file.upload.total;if(__file.status=="error")
_report.total_fail++;else if(__file.upload.progress==100&&__file.status=="success")
_report.total_done++;else _report.active++}
_report.progress=Math.round(_report.total_size_uped/_report.total_size*100);_report.progress=_report.progress>100?100:_report.progress;$(document).find(".file_input_wrapper."+ID).addClass("_doing").find(".mask_text").text(_report.progress+"%")
$(document).find(".file_input_wrapper."+ID+" .mask .progress").css("width",_report.progress+"%");if(_report.total_fail+_report.total_done==_report.total_files&&_report.total_files>=1&&_report.total_active==0){var __done=!0;var __response=null;try{__response=JSON.parse(myDropzone.files[0].xhr.responseText)}catch(e){__done=!1}
console.log(__done,__response,ID,myDropzone);window.bof_input.callback(__done,__response,ID)}},callbefore:function(ID){$(document).find(".file_input_wrapper."+ID).addClass("bof_upload").addClass("_started").removeClass("_done").removeClass("_doing").removeClass("_failed").find(".mask_text").text("Wait ...")},callback:function(sta,data,ID){$(document).find("#"+ID).remove();$(document).find(".file_input_wrapper."+ID).removeClass("_doing");$(document).find(".file_input_wrapper."+ID+" .mask .progress").css("width","0");console.log(sta,data,ID);if(sta?data.messages[0]=="done":!1){$(document).find(".file_input_wrapper."+ID).addClass("_done").find(".mask_text").text("done");$(document).find(".file_input_wrapper."+ID+" .ci").val(data.file_id);$(document).find(".file_input_wrapper."+ID+" .cp").val(data.file_pass);$(document).find(".file_input_wrapper."+ID).addClass("type_"+data.type)
$(document).find(".file_input_wrapper."+ID).addClass("has_preview");if(data.file_preview){$(document).find(".file_input_wrapper."+ID+" .preview").css("background-image","url('"+data.file_preview+"')")}
setTimeout(function(){if($(document).find(".file_input_wrapper."+ID).hasClass("_done")){$(document).find(".file_input_wrapper."+ID).removeClass("_done").find(".mask_text").text("upload")}},2500)}else{$(document).find(".file_input_wrapper."+ID).addClass("_failed").find(".mask_text").text(data.messages[0])}
$(document).trigger("bof_input_callback",{sta:sta,data:data,ID:ID})},exe_display_rules:function($inputs){for(var i=0;i<Object.keys($inputs).length;i++){var __input_key=Object.keys($inputs)[i];var __input=$inputs[__input_key];if(__input.display_on){$(document).find("#item_"+__input_key).addClass("hideByRules");var __rules=__input.display_on;var __cond=__input.display_on_cond?__input.display_on_cond:"and";var ___met=null;var ___met_all=!0;var ___met_one=!1;for(var z=0;z<Object.keys(__rules).length;z++){var __rule_key=Object.keys(__rules)[z];var __target_input=$inputs[__rule_key].input;var __target_dom=$(document).find("[name="+__target_input.name+"]");var __target_value=null;if(__target_input.type=="text"||__target_input.type=="textarea"||__target_input.type=="hidden")
__target_value=__target_dom.val();else if(__target_input.type=="select")
__target_value=__target_dom.find("option:selected").val();else if(__target_input.type=="select_i")
__target_value=$(document).find("[name="+__target_input.name+"]:checked").val();else if(__target_input.type=="checkbox")
__target_value=$(document).find("[name="+__target_input.name+"]").is(":checked");else bof.log("app.ui.content_single.exe_display_rules => failed to get __target_value for type:"+__target_input.type);var __rule=__rules[__rule_key];var __rule_cond=__rule[0];var __rule_args=__rule[1];if(__rule_cond=="equal"){if(__target_value==__rule_args)
___met_one=!0;else ___met_all=!1}else if(__rule_cond=="in_array"){if(__rule_args.indexOf(__target_value)>-1)
___met_one=!0;else ___met_all=!1}else if(__rule_cond=="in_array"){if(__rule_args.indexOf(__target_value)>-1)
___met_one=!0;else ___met_all=!1}else{bof.log("app.ui.content_single.exe_display_rules => failed to run condition "+__rule_cond)}}
if(__cond=="and"&&___met_all)
___met=!0;else if(__cond=="or"&&___met_one)
___met=!0;else ___met=!1;if(___met){$(document).find("#item_"+__input_key).removeClass("hideByRules")}}}},object_selector_ini:function(defPages,objects){var objects_option=[["_defs","App Pages"]];var objects_inputs={_defs:{"title":"App Page","input":{"name":"_defs","type":"select","options":defPages},"display_on":{object_type:["equal","_defs"]},"group":"b",}};for(var i=0;i<Object.keys(objects).length;i++){var object_name=Object.keys(objects)[i];var object_data=objects[object_name];objects_option.push([object_name,object_data.label]);object_data.selector.display_on={object_type:["equal",object_name]}
object_data.selector.group="b";objects_inputs["object_"+object_name]=object_data.selector}
var inputs={object_type:{title:"Object type",tip:"What kind of object you wish to make link to? For example if you wish to make a link to a page, select 'page'. To link a blog-post, select `Blog-Post`",input:{name:"object_type",type:"select",options:objects_option},group:"b"}};var $html="";$html=$html+"<div class='modal_hover close_opm'></div>";$html=$html+"<div class='modal_wrapper opm_wrapper'><div class='modal opm'>";$html=$html+"<div class='title'>Find a link<span class='material-icons-outlined close_opm'>close</span></div>";window.bof_modal.render_inputs($.extend(inputs,objects_inputs)).done(function(inputs_rendered){if(inputs_rendered)
$html=$html+"<div class='inputs'>"+inputs_rendered+"</div>";$html=$html+"<div class='buttons'>";$html=$html+"<div class='button'><a class='btn btn-primary execute_opm'>Get link</a></div>";$html=$html+"<div class='button'><a class='btn btn-secondary close_opm'>Back</a></div>";$html=$html+"</div>";$html=$html+"</div></div>";$("body").append($html);window.bof_input.exe_display_rules($.extend(inputs,objects_inputs));$(document).on("change",".modal.opm .bof_input",function(e){window.bof_input.exe_display_rules($.extend(inputs,objects_inputs))})});$(document).on("click",".close_opm",function(e){window.bof_input.object_selector_off()});$(document).on("click",".modal.opm .buttons .btn-primary",function(e){var Type=$(document).find(".modal.opm select[name=object_type] option:selected").val();var Id=$(document).find(".modal.opm .setting_wrapper:not(.hideByRules) input._ids").val();if(Type=="_defs"){var Link=$(document).find(".modal.opm .setting_wrapper:not(.hideByRules) select[name=_defs] option:checked").val();$(document).find(".modal input[name=href]").val(Link);window.bof_input.object_selector_off();return}
if(!Id){alert("Select an item first");return}
$(this).text("Wait ...");window.becli.exe({endpoint:"menuBuilder_get_link",post:{type:Type,ID:Id},callBack:function(sta,data){window.bof_input.object_selector_off();if(sta){if(data.link){$(document).find(".modal input[name=href]").val(data.link)}}}})})},object_selector_off:function(){$(document).find(".opm_wrapper").remove();$(document).find(".close_opm.modal_hover").remove();$(document).off("change",".modal.opm .bof_input");$(document).off("click",".close_opm");$(document).off("click",".modal.opm .buttons .btn-primary")}}