<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0d7774344a8d6fe903a9d15c4bf0c53b
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Statickidz\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Statickidz\\' => 
        array (
            0 => __DIR__ . '/..' . '/statickidz/php-google-translate-free/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0d7774344a8d6fe903a9d15c4bf0c53b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0d7774344a8d6fe903a9d15c4bf0c53b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0d7774344a8d6fe903a9d15c4bf0c53b::$classMap;

        }, null, ClassLoader::class);
    }
}
