<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitaf8cf639c881f585ebcdc22eac3b5da3
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WhichBrowser\\' => 13,
        ),
        'P' => 
        array (
            'Psr\\Cache\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WhichBrowser\\' => 
        array (
            0 => __DIR__ . '/..' . '/whichbrowser/parser/src',
            1 => __DIR__ . '/..' . '/whichbrowser/parser/tests/src',
        ),
        'Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitaf8cf639c881f585ebcdc22eac3b5da3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitaf8cf639c881f585ebcdc22eac3b5da3::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitaf8cf639c881f585ebcdc22eac3b5da3::$classMap;

        }, null, ClassLoader::class);
    }
}
